language: python

os:   linux
dist: bionic

python:
    - '3.8'

branches:
    only:
        - '1.9'

services:
    - docker

env:
    - REPOSITORY_URL=https://github.com/${TRAVIS_REPO_SLUG}.git

install:
    - >
        docker build
            --rm
            --build-arg DOCKER_IMAGE_PYTHON=${DOCKER_IMAGE_PYTHON}
            --cache-from ${DOCKER_IMAGE_PYTHON}
            -t ${DOCKER_IMAGE_PYTHON_BASE}
            .deploy/docker/python/base

script:
    # Download the previous gh-pages content
    - >
        git clone
            ${REPOSITORY_URL}
            --branch gh-pages
            build
    # Remove the unnecessary content
    - >
        rm -rf
            build/${TRAVIS_BRANCH}
            build/.git
    # Build the current doc
    - >
        docker run
            --rm
            --name builder
            -v ${PWD}:/var/www
            ${DOCKER_IMAGE_PYTHON_BASE}
            mkdocs build

deploy:
    provider:      pages
    skip_cleanup:  true
    github_token:  ${GITHUB_TOKEN}
    local_dir:     build
    target_branch: gh-pages
