language: python

os:   linux
dist: bionic

python:
    - '3.8'

branches:
    only:
        - '1.9'

services:
    - docker

install:
    - >
        docker build
        --rm
        --build-arg DOCKER_IMAGE_PYTHON=${DOCKER_IMAGE_PYTHON}
        --cache-from ${DOCKER_IMAGE_PYTHON}
        -t ${DOCKER_IMAGE_PYTHON_BASE}
        .deploy/docker/python/base

script:
    - >
        docker run
        --rm
        --name composer-doc-pt-br
        -v ${PWD}:/var/www
        ${DOCKER_IMAGE_PYTHON_BASE}
        mkdocs build

deploy:
    provider:      pages
    skip_cleanup:  true
    github_token:  ${GITHUB_TOKEN}
    local_dir:     build
    target_branch: gh-pages
    on:
        branch: '1.9'
