version: "3.8"

services:
    python:
        image: ${DOCKER_IMAGE_PYTHON_BASE}
        build:
            context: ""
            dockerfile: ../docker/python/base/Dockerfile
            args:
                DOCKER_IMAGE_PYTHON: ${DOCKER_IMAGE_PYTHON}
        restart: always
        command: mkdocs serve -a 0.0.0.0:8000
        ports:
            - ${DEV_HOST_PORT_HTTP}:8000
        volumes:
            # folders
            - ../..:/var/www
        working_dir: /var/www
        env_file:
            # docker
            - .env
            # application
            - ../../.env.local
        user: ${DOCKER_HOST_UID}:${DOCKER_HOST_GID}
